<a href="<?php echo SITENAME. "/" ?>rememberit/applicationuser" title="Add an application username/password" class="dttooltip applicationuser"><img src=<?php echo IMAGES_PATH . "/icons/applicationuser.png"; ?> /><span class="iconTitle">Application User</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/phonebook" title="Add a phonebook entry" class="dttooltip" style="color:#6c1c18;"><img src=<?php echo IMAGES_PATH . "/icons/phonebook.png"; ?> /><span class="iconTitle">Phone Book</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/blog" title="Add a blog account credentials" class="dttooltip" style="color:#cd4e0e;"><img src=<?php echo IMAGES_PATH . "/icons/blog.png"; ?> /><span class="iconTitle">Blog Account</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/database" title="Add a database credentials" class="dttooltip" style="color:#333;"><img src=<?php echo IMAGES_PATH . "/icons/database.png"; ?> /><span class="iconTitle">Database Credentials</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/email" title="Add an email account" class="dttooltip" style="color:#ab8341;"><img src=<?php echo IMAGES_PATH . "/icons/email.png"; ?> /><span class="iconTitle">Email Account</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/forum" title="Add a forum account" class="dttooltip" style="color:#179a1d;"><img src=<?php echo IMAGES_PATH . "/icons/forum.png"; ?> /><span class="iconTitle">Forum Account</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/ftp" title="Add an FTP account" class="dttooltip" style="color:#b3720e;"><img src=<?php echo IMAGES_PATH . "/icons/ftp.png"; ?> /><span class="iconTitle">FTP Account</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/mobile" title="Add a Mobile Application account" class="dttooltip" style="color:#bd0d71;"><img src=<?php echo IMAGES_PATH . "/icons/mobile.png"; ?> /><span class="iconTitle">Mobile Application</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/pcuser" title="Add a PC username/password" class="dttooltip" style="color:#0e5711;"><img src=<?php echo IMAGES_PATH . "/icons/pcuser.png"; ?> /><span class="iconTitle">PC User</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/web" title="Add an application login credentials" class="dttooltip" style="color:#b3720e;"><img src=<?php echo IMAGES_PATH . "/icons/web.png"; ?> /><span class="iconTitle">Website Credentials</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/address" title="Add an address" class="dttooltip" style="color:#333;"><img src=<?php echo IMAGES_PATH . "/icons/addresses.png"; ?> /><span class="iconTitle">Addresses</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/productkey" title="Add a product Key" class="dttooltip" style="color:#900;"><img src=<?php echo IMAGES_PATH . "/icons/keys.png"; ?> /><span class="iconTitle">Product Keys</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/download" title="Add a download link" class="dttooltip" style="color:#ab8341;"><img src=<?php echo IMAGES_PATH . "/icons/downloads.png"; ?> /><span class="iconTitle">Download Links</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/favorite" title="Add a favorite link" class="dttooltip" style="color:#cd4e0e;"><img src=<?php echo IMAGES_PATH . "/icons/favorites.png"; ?> /><span class="iconTitle">Favorites</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/favorite" title="Add a note" class="dttooltip"><img src=<?php echo IMAGES_PATH . "/icons/notes.png"; ?> /><span class="iconTitle">Notes</span></a>
<a id="search" href="<?php echo SITENAME. "/" ?>rememberit/search" title="Search for an item" class="dttooltip rItem" style="color:#607a97;"><img src=<?php echo IMAGES_PATH . "/icons/search.png"; ?> /><span class="iconTitle">Search</span></a>
<a id="help" href="<?php echo SITENAME. "/" ?>rememberit/help" title="How to use our service?" class="dttooltip rItem" style="color:#000;"><img src=<?php echo IMAGES_PATH . "/icons/help.png"; ?> /><span class="iconTitle">Help</span></a>
<a id="settings" href="<?php echo SITENAME. "/" ?>rememberit/settings" title="Adjust your settings" class="dttooltip rItem" style="color:#400009;"><img src=<?php echo IMAGES_PATH . "/icons/control.png"; ?> /><span class="iconTitle">Settings</span></a>
<a href="<?php echo SITENAME. "/" ?>rememberit/logout" title="Logout" class="dttooltip" style="color:#900;"><img src=<?php echo IMAGES_PATH . "/icons/logoutbig.png"; ?> /><span class="iconTitle">Logout</span></a>